language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind scons

compiler:
  - clang
  - gcc

script:
  - scons
  - valgrind --suppressions=valgrind.supp ./test/test
